// <auto-generated />
using System;
using ExpenseLite.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseLite.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpenseLiteDbContext))]
    [Migration("20260717064836_AddCashAdvances")]
    partial class AddCashAdvances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseLite.Domain.CashAdvances.CashAdvance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AdvancedAt")
                        .HasColumnType("date")
                        .HasColumnName("advanced_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payee_name");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("purpose");

                    b.HasKey("Id");

                    b.ToTable("cash_advances", (string)null);
                });

            modelBuilder.Entity("ExpenseLite.Domain.ExpenseReports.ExpenseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("applicant_name");

                    b.Property<Guid?>("CashAdvanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("cash_advance_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("expense_reports", (string)null);
                });

            modelBuilder.Entity("ExpenseLite.Domain.CashAdvances.CashAdvance", b =>
                {
                    b.OwnsOne("ExpenseLite.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CashAdvanceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.HasKey("CashAdvanceId");

                            b1.ToTable("cash_advances");

                            b1.WithOwner()
                                .HasForeignKey("CashAdvanceId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("ExpenseLite.Domain.ExpenseReports.ExpenseReport", b =>
                {
                    b.OwnsOne("ExpenseLite.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseReportId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("total_amount");

                            b1.HasKey("ExpenseReportId");

                            b1.ToTable("expense_reports");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseReportId");
                        });

                    b.OwnsMany("ExpenseLite.Domain.ExpenseReports.ExpenseDetail", "Details", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("category");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.Property<DateOnly>("ExpenseDate")
                                .HasColumnType("date")
                                .HasColumnName("expense_date");

                            b1.Property<Guid>("expense_report_id")
                                .HasColumnType("uuid")
                                .HasColumnName("expense_report_id");

                            b1.HasKey("Id");

                            b1.HasIndex("expense_report_id");

                            b1.ToTable("expense_details", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("expense_report_id");

                            b1.OwnsOne("ExpenseLite.Domain.ValueObjects.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("ExpenseDetailId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("amount");

                                    b2.HasKey("ExpenseDetailId");

                                    b2.ToTable("expense_details");

                                    b2.WithOwner()
                                        .HasForeignKey("ExpenseDetailId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.Navigation("Details");

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
